package com.belajarandroid.jetpacksubmission1.utils;

import com.belajarandroid.jetpacksubmission1.data.FilmEntity;

import java.util.ArrayList;
import java.util.List;

public class DataDummy {

    public static List<FilmEntity> generateDummyMovie() {

        ArrayList<FilmEntity> movie = new ArrayList<>();

        movie.add(new FilmEntity("m01",
                "movie",
                "/xJUILftRf6TJxloOgrilOTJfeOn.jpg",
                "/5BwqwxMEjeFtdknRV792Svo0K1v.jpg",
                "Ad Astra",
                "Sep 17, 2019",
                "6.0",
                "428.09",
                "Science Fiction, Drama, Thriller, Adventure, Mystery",
                "The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.",
                "2 hours 3 minutes",
                "Released",
                "$87,500,000",
                "$127,175,922",
                "false"));

        movie.add(new FilmEntity("m02",
                "movie",
                "/AuGiPiGMYMkSosOJ3BQjDEAiwtO.jpg",
                "/ds9GKAMhxv5AbprmZ2xCpK8FiEG.jpg",
                "1917",
                "Dec 10, 2019",
                "8.1",
                "244.49",
                "War, Drama, History, Action",
                "At the height of the First World War, two young British soldiers, Schofield and Blake are given a seemingly impossible mission. In a race against time, they must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers—Blake's own brother among them.",
                "1 hours 59 minutes",
                "Released",
                "$100,000,000",
                "$200,483,309",
                "false"));

        movie.add(new FilmEntity("m03",
                "movie",
                "/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
                "/iUspPEAjhUUrLYKntTnKupt3eqV.jpg",
                "Bad Boys For Life",
                "Jan 15, 2020",
                "6.6",
                "205.327",
                "Thriller, Action, Crime",
                "Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.",
                "0 hour 0 minute",
                "Released",
                "$0",
                "$0",
                "false"));

        movie.add(new FilmEntity("m04",
                "movie",
                "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
                "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
                "Joker",
                "Oct 02, 2019",
                "8.3",
                "171.92",
                "Crime, Thriller, Drama",
                "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
                "2 hours 2 minutes",
                "Released",
                "$55,000,000",
                "$1,060,753,468",
                "false"));

        movie.add(new FilmEntity("m05",
                "movie",
                "/p69QzIBbN06aTYqRRiCOY1emNBh.jpg",
                "/sZAXOoOMyCbBskmqR0f4LShxXtw.jpg",
                "Doctor Sleep",
                "Oct 30, 2019",
                "7.1",
                "145.365",
                "Horror, Drama, Fantasy",
                "Still irrevocably scarred by the trauma he endured as a child at the Overlook, Dan Torrance has fought to find some semblance of peace. But that peace is shattered when he encounters Abra, a courageous teenager with her own powerful extrasensory gift, known as the 'shine'.\\\" Instinctively recognising that Dan shares her power, Abra has sought him out, desperate for his help against the merciless Rose the Hat and her followers.",
                "2 hours 32 minutes",
                "Released",
                "$45,000,000",
                "$70,209,589",
                "false"));

        movie.add(new FilmEntity("m06",
                "movie",
                "/yJdeWaVXa2se9agI6B4mQunVYkB.jpg",
                "/ekP6EVxL81lZ4ivcqPsoZ72rY0h.jpg",
                "Ip Man 4: The Finale",
                "Dec 20, 2019",
                "5.8",
                "156.889",
                "Action, Drama, History",
                "Following the death of his wife, Ip Man travels to San Francisco to ease tensions between the local kung fu masters and his star student, Bruce Lee, while searching for a better future for his son.",
                "1 hour 45 minutes",
                "Released",
                "$52,000,000",
                "$0",
                "false"));

        movie.add(new FilmEntity("m07",
                "movie",
                "/s5HQf2Gb3lIO2cRcFwNL9sn1o1o.jpg",
                "/1n00NlOGRFZVs8coBxyZLm5l4EC.jpg",
                "Transformer: The Last Knight",
                "Jun 16, 2017",
                "6.0",
                "83.858",
                "Action, Science Fiction, Thriller, Adventure",
                "Autobots and Decepticons are at war, with humans on the sidelines. Optimus Prime is gone. The key to saving our future lies buried in the secrets of the past, in the hidden history of Transformers on Earth.",
                "2 hours 29 minutes",
                "Released",
                "$217,000,000",
                "$605,425,157",
                "false"));

        movie.add(new FilmEntity("m08",
                "movie",
                "/vqzNJRH4YyquRiWxCCOH0aXggHI.jpg",
                "/riTANvQ8GKmQbgtC1ps3OfkU43A.jpg",
                "Terminator: Dark Fate",
                "Oct 23, 2019",
                "6.2",
                "138.576",
                "Action, Science Fiction",
                "Decades after Sarah Connor prevented Judgment Day, a lethal new Terminator is sent to eliminate the future leader of the resistance. In a fight to save mankind, battle-hardened Sarah Connor teams up with an unexpected ally and an enhanced super soldier to stop the deadliest Terminator yet.",
                "2 hours 8 minutes",
                "Released",
                "$185,000,000",
                "$233,685,077",
                "false"));

        movie.add(new FilmEntity("m09",
                "movie",
                "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
                "/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg",
                "Star Wars: The Rise of Skywalker",
                "Dec 18, 2019",
                "6.5",
                "119.03",
                "Action, Adventure, Science Fiction",
                "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
                "2 hours 22 minutes",
                "Released",
                "$250,000,000",
                "$956,030,690",
                "false"));

        movie.add(new FilmEntity("m10",
                "movie",
                "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
                "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
                "Parasite",
                "May 30, 2019",
                "8.6",
                "106.013",
                "Comedy, Thriller, Drama",
                "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
                "2 hours 12 minutes",
                "Released",
                "$11,363,000",
                "$132,338,654",
                "false"));

        return movie;
    }

    public static List<FilmEntity> generateDummyShow() {
        ArrayList<FilmEntity> show = new ArrayList<>();

        show.add(new FilmEntity("s01",
                "tv",
                "/lHZ4xqGQlmyiFTOVtwnNpTcZgkd.jpg",
                "/q54k3tg5VjezBagGRtFamVqdY7L.jpg",
                "Insatiable",
                "Aug 10, 2018",
                "7.6",
                "754.632",
                "Drama, Comedy",
                "A bullied teenager turns to beauty pageants as a way to exact her revenge, with the help of a disgraced coach who soon realizes he's in over his head.",
                "0 hour 45 minutes",
                "Returning Series",
                "2",
                "22",
                "true"));

        show.add(new FilmEntity("s02",
                "tv",
                "/jQNOzoiaIQWxJAx8OUighnvnhRA.jpg",
                "/gVVaukIifGJD78llZKgyT5FQbAe.jpg",
                "Thieves of the Wood",
                "Jan 02, 2020",
                "5.6",
                "468.515",
                "Drama, Mystery",
                "Charismatic highwayman Jan de Lichte leads the oppressed and downtrodden in a revolt against the corrupt aristocracy of 18th-century Belgium.",
                "1 hours 0 minute",
                "Returning Series",
                "1",
                "10",
                "true"));

        show.add(new FilmEntity("s03",
                "tv",
                "/gKG5QGz5Ngf8fgWpBsWtlg5L2SF.jpg",
                "/dKxkwAJfGuznW8Hu0mhaDJtna0n.jpg",
                "Arrow",
                "Oct 10, 2012",
                "5.9",
                "292.791",
                "Crime, Drama, Mystery",
                "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.",
                "0 hour 42 minutes",
                "Ended",
                "8",
                "170",
                "false"));

        show.add(new FilmEntity("s04",
                "tv",
                "/qcr9bBY6MVeLzriKCmJOv1562uY.jpg",
                "/f5uNbUC76oowt5mt5J9QlqrIYQ6.jpg",
                "The Simpsons",
                "Dec 17, 1989",
                "7.2",
                "164.056",
                "Animation, Comedy",
                "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
                "0 hour 22 minutes",
                "Returning Series",
                "31",
                "673",
                "true"));

        show.add(new FilmEntity("s05",
                "tv",
                "/nIlAKIrLKxOeoEnc0Urb65yNCp.jpg",
                "/mK286PAkhgLJqk5cO0BCmFLkNE7.jpg",
                "Star Trek: Picard",
                "Jan 23, 2020",
                "8.6",
                "178.002",
                "Sci-Fi & Fantasy",
                "Star Trek: Picard features Sir Patrick Stewart reprising his iconic role as Jean-Luc Picard, which he played for seven seasons on Star Trek: The Next Generation. Set twenty years after the events of Star Trek Nemesis, this series follow the now-retired Admiral Picard into the next chapter of his life.",
                "0 hour 44 minutes",
                "Returning Series",
                "1",
                "10",
                "true"));

        show.add(new FilmEntity("s06",
                "tv",
                "/KoYWXbnYuS3b0GyQPkbuexlVK9.jpg",
                "/o9OKe3M06QMLOzTl3l6GStYtnE9.jpg",
                "Supernatural",
                "Sep 13, 2005",
                "7.5",
                "160.463",
                "Drama, Mystery, Sci-Fi & Fantasy",
                "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way.",
                "0 hour 45 minutes",
                "Returning Series",
                "15",
                "320",
                "true"));

        show.add(new FilmEntity("s07",
                "tv",
                "/qJdfO3ahgAMf2rcmhoqngjBBZW1.jpg",
                "/mzzHr6g1yvZ05Mc7hNj3tUdy2bM.jpg",
                "Rick and Morty",
                "Dec 02, 2013",
                "8.6",
                "154.306",
                "Animation, Comedy, Sci-Fi & Fantasy",
                "Rick is a mentally-unbalanced but scientifically-gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
                "0 hour 22 minutes",
                "Returning Series",
                "4",
                "36",
                "true"));

        show.add(new FilmEntity("s08",
                "tv",
                "/cDDb7WA2i7cENhkEEjXEDrXGyNL.jpg",
                "/nfH8SZJVOxcBlFaqqtoqS5hHizG.jpg",
                "Doctor Who",
                "Mar 26, 2005",
                "7.0",
                "121.924",
                "Drama, Sci-Fi & Fantasy",
                "The Doctor is a Time Lord: a 900 year old alien with 2 hearts, part of a gifted civilization who mastered time travel. The Doctor saves planets for a living—more of a hobby actually, and the Doctor's very, very good at it.",
                "1 hour 20 minutes",
                "Returning Series",
                "12",
                "144",
                "true"));

        show.add(new FilmEntity("s09",
                "tv",
                "/6t6r1VGQTTQecN4V0sZeqsmdU9g.jpg",
                "/kOvt2BOOwSAQCT8yo3pM3X2GXjh.jpg",
                "Law & Order: Special Victims Unit",
                "Sep 20, 1999",
                "6.5",
                "157.393",
                "Crime, Drama",
                "In the criminal justice system, sexually-based offenses are considered especially heinous. In New York City, the dedicated detectives who investigate these vicious felonies are members of an elite squad known as the Special Victims Unit. These are their stories.",
                "0 hour 43 minutes",
                "Returning Series",
                "21",
                "474",
                "true"));

        show.add(new FilmEntity("s10",
                "tv",
                "/ff1zhqvwfS5HvRNcA5UFrH0PA2q.jpg",
                "/aq2yEMgRQBPfRkrO0Repo2qhUAT.jpg",
                "Vikings",
                "Mar 03, 2013",
                "7.5",
                "125.564",
                "Drama",
                "The adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.",
                "0 hour 44 minutes",
                "Returning Series",
                "6",
                "79",
                "true"));

        return show;
    }
}
